name: Android CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - sandbox
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create temporary release key
        run: |
          mkdir -p ~/.android
          keytool \
            -genkey \
            -keystore ~/.android/release.keystore \
            -keyalg RSA \
            -keysize 2048 \
            -validity 90 \
            -alias release \
            -dname "cn=GitHub Action (commit ${{ github.sha }}), o=GitHub, c=US" \
            -storepass android \
            -keypass android
          echo "storeFile=~/.android/release.keystore" >> keystore.properties
          echo "storePassword=android" >> keystore.properties
          echo "keyAlias=release" >> keystore.properties
          echo "keyPassword=android" >> keystore.properties

      - run:  ./gradlew --no-daemon --info build

      - uses: android-actions/annotate-lint-results@v1.0.15
        if: ${{ always() }}
        with:
          token: ${{ github.token }}

